[2023-03-10 08:50:25,653] {processor.py:153} INFO - Started process (PID=6548) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:50:25,653] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:50:25,654] {logging_mixin.py:115} INFO - [2023-03-10 08:50:25,654] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:50:25,666] {logging_mixin.py:115} INFO - [2023-03-10 08:50:25,666] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:50:25,666] {logging_mixin.py:115} INFO - [2023-03-10 08:50:25,666] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:50:25,666] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:50:25,674] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-03-10 08:51:42,503] {processor.py:153} INFO - Started process (PID=7167) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:51:42,506] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:51:42,507] {logging_mixin.py:115} INFO - [2023-03-10 08:51:42,506] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:51:42,532] {logging_mixin.py:115} INFO - [2023-03-10 08:51:42,532] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:51:42,532] {logging_mixin.py:115} INFO - [2023-03-10 08:51:42,532] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:51:42,532] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:51:42,543] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-10 08:52:22,632] {processor.py:153} INFO - Started process (PID=7376) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:22,633] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:52:22,634] {logging_mixin.py:115} INFO - [2023-03-10 08:52:22,633] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:22,649] {logging_mixin.py:115} INFO - [2023-03-10 08:52:22,648] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:52:22,649] {logging_mixin.py:115} INFO - [2023-03-10 08:52:22,649] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:52:22,649] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:22,660] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-03-10 08:52:57,747] {processor.py:153} INFO - Started process (PID=7556) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:57,749] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:52:57,751] {logging_mixin.py:115} INFO - [2023-03-10 08:52:57,751] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:57,794] {logging_mixin.py:115} INFO - [2023-03-10 08:52:57,794] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:52:57,794] {logging_mixin.py:115} INFO - [2023-03-10 08:52:57,794] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:52:57,795] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:52:57,807] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2023-03-10 08:53:34,561] {processor.py:153} INFO - Started process (PID=7680) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:53:34,564] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:53:34,565] {logging_mixin.py:115} INFO - [2023-03-10 08:53:34,565] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:53:34,618] {logging_mixin.py:115} INFO - [2023-03-10 08:53:34,617] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:53:34,618] {logging_mixin.py:115} INFO - [2023-03-10 08:53:34,618] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:53:34,619] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:53:34,636] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2023-03-10 08:54:10,788] {processor.py:153} INFO - Started process (PID=7841) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:10,793] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:54:10,794] {logging_mixin.py:115} INFO - [2023-03-10 08:54:10,794] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:10,828] {logging_mixin.py:115} INFO - [2023-03-10 08:54:10,828] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:54:10,829] {logging_mixin.py:115} INFO - [2023-03-10 08:54:10,828] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:54:10,829] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:10,840] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-03-10 08:54:50,393] {processor.py:153} INFO - Started process (PID=7884) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:50,396] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:54:50,398] {logging_mixin.py:115} INFO - [2023-03-10 08:54:50,397] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:50,427] {logging_mixin.py:115} INFO - [2023-03-10 08:54:50,426] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:54:50,427] {logging_mixin.py:115} INFO - [2023-03-10 08:54:50,427] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:54:50,427] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:54:50,437] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2023-03-10 08:55:32,563] {processor.py:153} INFO - Started process (PID=7928) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:55:32,568] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:55:32,570] {logging_mixin.py:115} INFO - [2023-03-10 08:55:32,570] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:55:32,618] {logging_mixin.py:115} INFO - [2023-03-10 08:55:32,617] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:55:32,618] {logging_mixin.py:115} INFO - [2023-03-10 08:55:32,618] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:55:32,618] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:55:32,632] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-03-10 08:56:11,079] {processor.py:153} INFO - Started process (PID=8048) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:11,080] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:56:11,080] {logging_mixin.py:115} INFO - [2023-03-10 08:56:11,080] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:11,094] {logging_mixin.py:115} INFO - [2023-03-10 08:56:11,094] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:56:11,094] {logging_mixin.py:115} INFO - [2023-03-10 08:56:11,094] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:56:11,094] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:11,102] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-03-10 08:56:47,432] {processor.py:153} INFO - Started process (PID=8313) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:47,434] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:56:47,435] {logging_mixin.py:115} INFO - [2023-03-10 08:56:47,435] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:47,484] {logging_mixin.py:115} INFO - [2023-03-10 08:56:47,483] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:56:47,484] {logging_mixin.py:115} INFO - [2023-03-10 08:56:47,484] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:56:47,484] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:56:47,498] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2023-03-10 08:57:22,701] {processor.py:153} INFO - Started process (PID=8365) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:57:22,705] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:57:22,707] {logging_mixin.py:115} INFO - [2023-03-10 08:57:22,706] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:57:22,778] {logging_mixin.py:115} INFO - [2023-03-10 08:57:22,777] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:57:22,778] {logging_mixin.py:115} INFO - [2023-03-10 08:57:22,778] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:57:22,779] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:57:22,795] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2023-03-10 08:58:02,168] {processor.py:153} INFO - Started process (PID=8406) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:02,171] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:58:02,173] {logging_mixin.py:115} INFO - [2023-03-10 08:58:02,172] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:02,202] {logging_mixin.py:115} INFO - [2023-03-10 08:58:02,201] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:58:02,202] {logging_mixin.py:115} INFO - [2023-03-10 08:58:02,202] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:58:02,202] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:02,211] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-03-10 08:58:38,246] {processor.py:153} INFO - Started process (PID=8446) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:38,249] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:58:38,252] {logging_mixin.py:115} INFO - [2023-03-10 08:58:38,251] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:38,302] {logging_mixin.py:115} INFO - [2023-03-10 08:58:38,302] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:58:38,302] {logging_mixin.py:115} INFO - [2023-03-10 08:58:38,302] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:58:38,303] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:58:38,316] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2023-03-10 08:59:15,868] {processor.py:153} INFO - Started process (PID=8500) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:59:15,870] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 08:59:15,872] {logging_mixin.py:115} INFO - [2023-03-10 08:59:15,871] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:59:15,901] {logging_mixin.py:115} INFO - [2023-03-10 08:59:15,901] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 08:59:15,902] {logging_mixin.py:115} INFO - [2023-03-10 08:59:15,902] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 08:59:15,902] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 08:59:15,921] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-03-10 09:00:24,516] {processor.py:153} INFO - Started process (PID=8774) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:24,519] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:00:24,521] {logging_mixin.py:115} INFO - [2023-03-10 09:00:24,521] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:24,568] {logging_mixin.py:115} INFO - [2023-03-10 09:00:24,568] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:00:24,569] {logging_mixin.py:115} INFO - [2023-03-10 09:00:24,569] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:00:24,569] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:24,585] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2023-03-10 09:00:59,765] {processor.py:153} INFO - Started process (PID=9035) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:59,769] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:00:59,769] {logging_mixin.py:115} INFO - [2023-03-10 09:00:59,769] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:59,788] {logging_mixin.py:115} INFO - [2023-03-10 09:00:59,788] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:00:59,789] {logging_mixin.py:115} INFO - [2023-03-10 09:00:59,789] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:00:59,789] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:00:59,801] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-03-10 09:02:15,697] {processor.py:153} INFO - Started process (PID=9502) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:15,701] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:02:15,702] {logging_mixin.py:115} INFO - [2023-03-10 09:02:15,702] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:15,726] {logging_mixin.py:115} INFO - [2023-03-10 09:02:15,726] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:02:15,727] {logging_mixin.py:115} INFO - [2023-03-10 09:02:15,727] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:02:15,727] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:15,736] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-03-10 09:02:53,581] {processor.py:153} INFO - Started process (PID=9858) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:53,587] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:02:53,589] {logging_mixin.py:115} INFO - [2023-03-10 09:02:53,589] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:53,626] {logging_mixin.py:115} INFO - [2023-03-10 09:02:53,626] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:02:53,627] {logging_mixin.py:115} INFO - [2023-03-10 09:02:53,626] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:02:53,627] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:02:53,640] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2023-03-10 09:03:29,804] {processor.py:153} INFO - Started process (PID=10062) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:03:29,807] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:03:29,809] {logging_mixin.py:115} INFO - [2023-03-10 09:03:29,809] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:03:29,864] {logging_mixin.py:115} INFO - [2023-03-10 09:03:29,863] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:03:29,864] {logging_mixin.py:115} INFO - [2023-03-10 09:03:29,864] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:03:29,865] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:03:29,886] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2023-03-10 09:04:05,056] {processor.py:153} INFO - Started process (PID=10142) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:05,059] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:04:05,060] {logging_mixin.py:115} INFO - [2023-03-10 09:04:05,060] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:05,088] {logging_mixin.py:115} INFO - [2023-03-10 09:04:05,087] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:04:05,088] {logging_mixin.py:115} INFO - [2023-03-10 09:04:05,088] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:04:05,088] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:05,097] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-03-10 09:04:38,906] {processor.py:153} INFO - Started process (PID=10215) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:38,910] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:04:38,910] {logging_mixin.py:115} INFO - [2023-03-10 09:04:38,910] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:38,924] {logging_mixin.py:115} INFO - [2023-03-10 09:04:38,924] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:04:38,924] {logging_mixin.py:115} INFO - [2023-03-10 09:04:38,924] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:04:38,924] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:04:38,934] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-03-10 09:05:15,883] {processor.py:153} INFO - Started process (PID=10260) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:15,885] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:05:15,886] {logging_mixin.py:115} INFO - [2023-03-10 09:05:15,886] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:15,910] {logging_mixin.py:115} INFO - [2023-03-10 09:05:15,909] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:05:15,910] {logging_mixin.py:115} INFO - [2023-03-10 09:05:15,910] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:05:15,910] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:15,925] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-03-10 09:05:50,937] {processor.py:153} INFO - Started process (PID=10385) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:50,939] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:05:50,941] {logging_mixin.py:115} INFO - [2023-03-10 09:05:50,940] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:50,992] {logging_mixin.py:115} INFO - [2023-03-10 09:05:50,991] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:05:50,992] {logging_mixin.py:115} INFO - [2023-03-10 09:05:50,992] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:05:50,993] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:05:51,008] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2023-03-10 09:06:27,083] {processor.py:153} INFO - Started process (PID=10448) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:06:27,086] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:06:27,088] {logging_mixin.py:115} INFO - [2023-03-10 09:06:27,087] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:06:27,141] {logging_mixin.py:115} INFO - [2023-03-10 09:06:27,141] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:06:27,141] {logging_mixin.py:115} INFO - [2023-03-10 09:06:27,141] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:06:27,142] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:06:27,156] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2023-03-10 09:07:05,467] {processor.py:153} INFO - Started process (PID=10639) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:05,469] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:07:05,471] {logging_mixin.py:115} INFO - [2023-03-10 09:07:05,470] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:05,500] {logging_mixin.py:115} INFO - [2023-03-10 09:07:05,500] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:07:05,500] {logging_mixin.py:115} INFO - [2023-03-10 09:07:05,500] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:07:05,501] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:05,511] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-03-10 09:07:45,951] {processor.py:153} INFO - Started process (PID=10709) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:45,954] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:07:45,956] {logging_mixin.py:115} INFO - [2023-03-10 09:07:45,955] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:46,012] {logging_mixin.py:115} INFO - [2023-03-10 09:07:46,010] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:07:46,012] {logging_mixin.py:115} INFO - [2023-03-10 09:07:46,012] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:07:46,013] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:07:46,033] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2023-03-10 09:08:26,963] {processor.py:153} INFO - Started process (PID=10768) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:08:26,966] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:08:26,968] {logging_mixin.py:115} INFO - [2023-03-10 09:08:26,968] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:08:27,016] {logging_mixin.py:115} INFO - [2023-03-10 09:08:27,016] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:08:27,017] {logging_mixin.py:115} INFO - [2023-03-10 09:08:27,016] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:08:27,017] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:08:27,031] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2023-03-10 09:09:05,921] {processor.py:153} INFO - Started process (PID=10853) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:05,922] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:09:05,923] {logging_mixin.py:115} INFO - [2023-03-10 09:09:05,923] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:05,935] {logging_mixin.py:115} INFO - [2023-03-10 09:09:05,935] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:09:05,935] {logging_mixin.py:115} INFO - [2023-03-10 09:09:05,935] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:09:05,935] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:05,942] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-03-10 09:09:46,149] {processor.py:153} INFO - Started process (PID=10986) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:46,154] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:09:46,155] {logging_mixin.py:115} INFO - [2023-03-10 09:09:46,155] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:46,183] {logging_mixin.py:115} INFO - [2023-03-10 09:09:46,183] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:09:46,183] {logging_mixin.py:115} INFO - [2023-03-10 09:09:46,183] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:09:46,184] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:09:46,195] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-03-10 09:10:23,678] {processor.py:153} INFO - Started process (PID=11103) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:10:23,679] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:10:23,680] {logging_mixin.py:115} INFO - [2023-03-10 09:10:23,680] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:10:23,703] {logging_mixin.py:115} INFO - [2023-03-10 09:10:23,702] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:10:23,703] {logging_mixin.py:115} INFO - [2023-03-10 09:10:23,703] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:10:23,703] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:10:23,713] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-10 09:11:06,359] {processor.py:153} INFO - Started process (PID=11209) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:06,361] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:11:06,362] {logging_mixin.py:115} INFO - [2023-03-10 09:11:06,362] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:06,380] {logging_mixin.py:115} INFO - [2023-03-10 09:11:06,379] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:11:06,380] {logging_mixin.py:115} INFO - [2023-03-10 09:11:06,380] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:11:06,380] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:06,389] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-10 09:11:42,126] {processor.py:153} INFO - Started process (PID=11265) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:42,133] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:11:42,136] {logging_mixin.py:115} INFO - [2023-03-10 09:11:42,136] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:42,172] {logging_mixin.py:115} INFO - [2023-03-10 09:11:42,171] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:11:42,172] {logging_mixin.py:115} INFO - [2023-03-10 09:11:42,172] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:11:42,172] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:11:42,184] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2023-03-10 09:12:21,319] {processor.py:153} INFO - Started process (PID=11374) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:12:21,322] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:12:21,323] {logging_mixin.py:115} INFO - [2023-03-10 09:12:21,323] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:12:21,382] {logging_mixin.py:115} INFO - [2023-03-10 09:12:21,381] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:12:21,383] {logging_mixin.py:115} INFO - [2023-03-10 09:12:21,383] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:12:21,383] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:12:21,399] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2023-03-10 09:13:01,995] {processor.py:153} INFO - Started process (PID=11426) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:02,001] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:13:02,003] {logging_mixin.py:115} INFO - [2023-03-10 09:13:02,003] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:02,069] {logging_mixin.py:115} INFO - [2023-03-10 09:13:02,068] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:13:02,070] {logging_mixin.py:115} INFO - [2023-03-10 09:13:02,069] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:13:02,070] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:02,091] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2023-03-10 09:13:42,037] {processor.py:153} INFO - Started process (PID=11518) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:42,040] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:13:42,043] {logging_mixin.py:115} INFO - [2023-03-10 09:13:42,042] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:42,095] {logging_mixin.py:115} INFO - [2023-03-10 09:13:42,094] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:13:42,095] {logging_mixin.py:115} INFO - [2023-03-10 09:13:42,095] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:13:42,095] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:13:42,108] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2023-03-10 09:14:17,310] {processor.py:153} INFO - Started process (PID=11643) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:17,313] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:14:17,314] {logging_mixin.py:115} INFO - [2023-03-10 09:14:17,314] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:17,347] {logging_mixin.py:115} INFO - [2023-03-10 09:14:17,346] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:14:17,347] {logging_mixin.py:115} INFO - [2023-03-10 09:14:17,347] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:14:17,347] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:17,358] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-03-10 09:14:59,037] {processor.py:153} INFO - Started process (PID=11690) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:59,039] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:14:59,039] {logging_mixin.py:115} INFO - [2023-03-10 09:14:59,039] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:59,051] {logging_mixin.py:115} INFO - [2023-03-10 09:14:59,050] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:14:59,051] {logging_mixin.py:115} INFO - [2023-03-10 09:14:59,051] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:14:59,051] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:14:59,059] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-03-10 09:15:34,449] {processor.py:153} INFO - Started process (PID=11747) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:15:34,451] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:15:34,452] {logging_mixin.py:115} INFO - [2023-03-10 09:15:34,452] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:15:34,474] {logging_mixin.py:115} INFO - [2023-03-10 09:15:34,474] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:15:34,474] {logging_mixin.py:115} INFO - [2023-03-10 09:15:34,474] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:15:34,474] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:15:34,485] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-10 09:16:18,163] {processor.py:153} INFO - Started process (PID=11839) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:18,169] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:16:18,171] {logging_mixin.py:115} INFO - [2023-03-10 09:16:18,171] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:18,246] {logging_mixin.py:115} INFO - [2023-03-10 09:16:18,244] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:16:18,247] {logging_mixin.py:115} INFO - [2023-03-10 09:16:18,247] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:16:18,247] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:18,270] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2023-03-10 09:16:57,239] {processor.py:153} INFO - Started process (PID=11940) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:57,248] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:16:57,251] {logging_mixin.py:115} INFO - [2023-03-10 09:16:57,250] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:57,304] {logging_mixin.py:115} INFO - [2023-03-10 09:16:57,304] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:16:57,305] {logging_mixin.py:115} INFO - [2023-03-10 09:16:57,305] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:16:57,305] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:16:57,319] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-03-10 09:17:33,776] {processor.py:153} INFO - Started process (PID=11998) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:17:33,778] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:17:33,779] {logging_mixin.py:115} INFO - [2023-03-10 09:17:33,779] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:17:33,799] {logging_mixin.py:115} INFO - [2023-03-10 09:17:33,799] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:17:33,799] {logging_mixin.py:115} INFO - [2023-03-10 09:17:33,799] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:17:33,799] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:17:33,809] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-10 09:18:11,861] {processor.py:153} INFO - Started process (PID=12052) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:11,865] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:18:11,866] {logging_mixin.py:115} INFO - [2023-03-10 09:18:11,866] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:11,886] {logging_mixin.py:115} INFO - [2023-03-10 09:18:11,886] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:18:11,886] {logging_mixin.py:115} INFO - [2023-03-10 09:18:11,886] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:18:11,886] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:11,897] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-10 09:18:51,281] {processor.py:153} INFO - Started process (PID=12172) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:51,285] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:18:51,286] {logging_mixin.py:115} INFO - [2023-03-10 09:18:51,286] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:51,312] {logging_mixin.py:115} INFO - [2023-03-10 09:18:51,311] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:18:51,312] {logging_mixin.py:115} INFO - [2023-03-10 09:18:51,312] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:18:51,312] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:18:51,330] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2023-03-10 09:19:28,458] {processor.py:153} INFO - Started process (PID=12256) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:19:28,463] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:19:28,464] {logging_mixin.py:115} INFO - [2023-03-10 09:19:28,463] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:19:28,480] {logging_mixin.py:115} INFO - [2023-03-10 09:19:28,480] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:19:28,480] {logging_mixin.py:115} INFO - [2023-03-10 09:19:28,480] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:19:28,481] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:19:28,489] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-03-10 09:20:09,579] {processor.py:153} INFO - Started process (PID=12315) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:09,581] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:20:09,582] {logging_mixin.py:115} INFO - [2023-03-10 09:20:09,582] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:09,606] {logging_mixin.py:115} INFO - [2023-03-10 09:20:09,605] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:20:09,606] {logging_mixin.py:115} INFO - [2023-03-10 09:20:09,606] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:20:09,606] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:09,620] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-10 09:20:50,448] {processor.py:153} INFO - Started process (PID=12400) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:50,456] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:20:50,458] {logging_mixin.py:115} INFO - [2023-03-10 09:20:50,458] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:50,507] {logging_mixin.py:115} INFO - [2023-03-10 09:20:50,506] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:20:50,507] {logging_mixin.py:115} INFO - [2023-03-10 09:20:50,507] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:20:50,507] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:20:50,520] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2023-03-10 09:21:25,350] {processor.py:153} INFO - Started process (PID=12485) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:21:25,352] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:21:25,353] {logging_mixin.py:115} INFO - [2023-03-10 09:21:25,352] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:21:25,378] {logging_mixin.py:115} INFO - [2023-03-10 09:21:25,378] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:21:25,379] {logging_mixin.py:115} INFO - [2023-03-10 09:21:25,378] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:21:25,379] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:21:25,389] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-03-10 09:22:05,019] {processor.py:153} INFO - Started process (PID=12607) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:05,020] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:22:05,021] {logging_mixin.py:115} INFO - [2023-03-10 09:22:05,021] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:05,039] {logging_mixin.py:115} INFO - [2023-03-10 09:22:05,039] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:22:05,039] {logging_mixin.py:115} INFO - [2023-03-10 09:22:05,039] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:22:05,040] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:05,055] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-03-10 09:22:44,669] {processor.py:153} INFO - Started process (PID=12712) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:44,671] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:22:44,674] {logging_mixin.py:115} INFO - [2023-03-10 09:22:44,673] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:44,741] {logging_mixin.py:115} INFO - [2023-03-10 09:22:44,740] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:22:44,742] {logging_mixin.py:115} INFO - [2023-03-10 09:22:44,741] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:22:44,742] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:22:44,760] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2023-03-10 09:23:24,865] {processor.py:153} INFO - Started process (PID=12767) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:23:24,869] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:23:24,870] {logging_mixin.py:115} INFO - [2023-03-10 09:23:24,870] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:23:24,897] {logging_mixin.py:115} INFO - [2023-03-10 09:23:24,896] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:23:24,897] {logging_mixin.py:115} INFO - [2023-03-10 09:23:24,897] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:23:24,898] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:23:24,914] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2023-03-10 09:24:09,172] {processor.py:153} INFO - Started process (PID=12997) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:09,175] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:24:09,177] {logging_mixin.py:115} INFO - [2023-03-10 09:24:09,176] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:09,215] {logging_mixin.py:115} INFO - [2023-03-10 09:24:09,214] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:24:09,215] {logging_mixin.py:115} INFO - [2023-03-10 09:24:09,215] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:24:09,215] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:09,225] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2023-03-10 09:24:45,225] {processor.py:153} INFO - Started process (PID=13214) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:45,230] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:24:45,231] {logging_mixin.py:115} INFO - [2023-03-10 09:24:45,231] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:45,250] {logging_mixin.py:115} INFO - [2023-03-10 09:24:45,250] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:24:45,250] {logging_mixin.py:115} INFO - [2023-03-10 09:24:45,250] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:24:45,251] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:24:45,261] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-10 09:25:20,681] {processor.py:153} INFO - Started process (PID=13272) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:25:20,683] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:25:20,684] {logging_mixin.py:115} INFO - [2023-03-10 09:25:20,683] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:25:20,724] {logging_mixin.py:115} INFO - [2023-03-10 09:25:20,723] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:25:20,725] {logging_mixin.py:115} INFO - [2023-03-10 09:25:20,724] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:25:20,725] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:25:20,763] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2023-03-10 09:28:48,043] {processor.py:153} INFO - Started process (PID=14254) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:28:48,044] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:28:48,044] {logging_mixin.py:115} INFO - [2023-03-10 09:28:48,044] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:28:48,058] {logging_mixin.py:115} INFO - [2023-03-10 09:28:48,058] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:28:48,058] {logging_mixin.py:115} INFO - [2023-03-10 09:28:48,058] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:28:48,058] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:28:48,068] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-03-10 09:29:55,149] {processor.py:153} INFO - Started process (PID=14837) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:29:55,153] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:29:55,155] {logging_mixin.py:115} INFO - [2023-03-10 09:29:55,154] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:29:55,214] {logging_mixin.py:115} INFO - [2023-03-10 09:29:55,213] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:29:55,214] {logging_mixin.py:115} INFO - [2023-03-10 09:29:55,214] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:29:55,215] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:29:55,228] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2023-03-10 09:30:33,154] {processor.py:153} INFO - Started process (PID=15152) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:30:33,157] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:30:33,158] {logging_mixin.py:115} INFO - [2023-03-10 09:30:33,158] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:30:33,205] {logging_mixin.py:115} INFO - [2023-03-10 09:30:33,205] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:30:33,205] {logging_mixin.py:115} INFO - [2023-03-10 09:30:33,205] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:30:33,206] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:30:33,218] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2023-03-10 09:31:09,411] {processor.py:153} INFO - Started process (PID=15295) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:31:09,412] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:31:09,413] {logging_mixin.py:115} INFO - [2023-03-10 09:31:09,413] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:31:09,429] {logging_mixin.py:115} INFO - [2023-03-10 09:31:09,428] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:31:09,429] {logging_mixin.py:115} INFO - [2023-03-10 09:31:09,429] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:31:09,429] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:31:09,441] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-10 09:32:54,305] {processor.py:153} INFO - Started process (PID=15822) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:32:54,309] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:32:54,311] {logging_mixin.py:115} INFO - [2023-03-10 09:32:54,311] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:32:54,364] {logging_mixin.py:115} INFO - [2023-03-10 09:32:54,363] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:32:54,364] {logging_mixin.py:115} INFO - [2023-03-10 09:32:54,364] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:32:54,364] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:32:54,378] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2023-03-10 09:33:34,380] {processor.py:153} INFO - Started process (PID=16165) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:33:34,382] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:33:34,384] {logging_mixin.py:115} INFO - [2023-03-10 09:33:34,384] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:33:34,406] {logging_mixin.py:115} INFO - [2023-03-10 09:33:34,406] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:33:34,407] {logging_mixin.py:115} INFO - [2023-03-10 09:33:34,406] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:33:34,407] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:33:34,415] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-03-10 09:34:52,526] {processor.py:153} INFO - Started process (PID=16749) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:34:52,527] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:34:52,527] {logging_mixin.py:115} INFO - [2023-03-10 09:34:52,527] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:34:52,543] {logging_mixin.py:115} INFO - [2023-03-10 09:34:52,543] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:34:52,544] {logging_mixin.py:115} INFO - [2023-03-10 09:34:52,543] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:34:52,544] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:34:52,554] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-03-10 09:35:28,709] {processor.py:153} INFO - Started process (PID=16828) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:35:28,711] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:35:28,712] {logging_mixin.py:115} INFO - [2023-03-10 09:35:28,712] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:35:28,734] {logging_mixin.py:115} INFO - [2023-03-10 09:35:28,734] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:35:28,734] {logging_mixin.py:115} INFO - [2023-03-10 09:35:28,734] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:35:28,734] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:35:28,742] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-03-10 09:36:24,183] {processor.py:153} INFO - Started process (PID=17293) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:36:24,183] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:36:24,184] {logging_mixin.py:115} INFO - [2023-03-10 09:36:24,184] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:36:24,199] {logging_mixin.py:115} INFO - [2023-03-10 09:36:24,199] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:36:24,199] {logging_mixin.py:115} INFO - [2023-03-10 09:36:24,199] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:36:24,199] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:36:24,207] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-03-10 09:40:34,932] {processor.py:153} INFO - Started process (PID=18173) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:40:34,935] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-10 09:40:34,936] {logging_mixin.py:115} INFO - [2023-03-10 09:40:34,936] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:40:34,988] {logging_mixin.py:115} INFO - [2023-03-10 09:40:34,987] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-10 09:40:34,989] {logging_mixin.py:115} INFO - [2023-03-10 09:40:34,989] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-10 09:40:34,989] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-10 09:40:35,020] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
