[2023-03-10 09:06:53,429] {processor.py:153} INFO - Started process (PID=10534) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:06:53,430] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:06:53,431] {logging_mixin.py:115} INFO - [2023-03-10 09:06:53,431] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:06:53,434] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:06:53,449] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.028 seconds
[2023-03-10 09:07:23,825] {processor.py:153} INFO - Started process (PID=10680) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:23,827] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:07:23,829] {logging_mixin.py:115} INFO - [2023-03-10 09:07:23,829] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:23,840] {logging_mixin.py:115} INFO - [2023-03-10 09:07:23,835] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7
    )
     ^
SyntaxError: invalid syntax
[2023-03-10 09:07:23,841] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:23,917] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.103 seconds
[2023-03-10 09:07:57,236] {processor.py:153} INFO - Started process (PID=10726) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:57,239] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:07:57,240] {logging_mixin.py:115} INFO - [2023-03-10 09:07:57,240] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:57,245] {logging_mixin.py:115} INFO - [2023-03-10 09:07:57,244] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    )
     ^
SyntaxError: invalid syntax
[2023-03-10 09:07:57,246] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:07:57,274] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.048 seconds
[2023-03-10 09:08:30,671] {processor.py:153} INFO - Started process (PID=10772) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:08:30,673] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:08:30,675] {logging_mixin.py:115} INFO - [2023-03-10 09:08:30,674] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:08:30,684] {logging_mixin.py:115} INFO - [2023-03-10 09:08:30,681] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:08:30,686] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:08:30,745] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.087 seconds
[2023-03-10 09:09:02,028] {processor.py:153} INFO - Started process (PID=10827) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:02,029] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:09:02,030] {logging_mixin.py:115} INFO - [2023-03-10 09:09:02,030] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:02,032] {logging_mixin.py:115} INFO - [2023-03-10 09:09:02,031] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:09:02,032] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:02,051] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.026 seconds
[2023-03-10 09:09:35,508] {processor.py:153} INFO - Started process (PID=10910) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:35,512] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:09:35,515] {logging_mixin.py:115} INFO - [2023-03-10 09:09:35,514] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:35,524] {logging_mixin.py:115} INFO - [2023-03-10 09:09:35,522] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:09:35,525] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:09:35,558] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.063 seconds
[2023-03-10 09:10:11,948] {processor.py:153} INFO - Started process (PID=11086) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:11,952] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:10:11,955] {logging_mixin.py:115} INFO - [2023-03-10 09:10:11,954] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:11,963] {logging_mixin.py:115} INFO - [2023-03-10 09:10:11,960] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:10:11,964] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:12,030] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.092 seconds
[2023-03-10 09:10:42,491] {processor.py:153} INFO - Started process (PID=11147) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:42,495] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:10:42,498] {logging_mixin.py:115} INFO - [2023-03-10 09:10:42,498] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:42,508] {logging_mixin.py:115} INFO - [2023-03-10 09:10:42,504] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:10:42,509] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:10:42,552] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.077 seconds
[2023-03-10 09:11:15,700] {processor.py:153} INFO - Started process (PID=11224) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:15,703] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:11:15,704] {logging_mixin.py:115} INFO - [2023-03-10 09:11:15,704] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:15,710] {logging_mixin.py:115} INFO - [2023-03-10 09:11:15,708] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    [minuto hora dia_mes mes dia/dias_da_semana]
            ^
SyntaxError: invalid syntax
[2023-03-10 09:11:15,711] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:15,738] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.045 seconds
[2023-03-10 09:11:50,702] {processor.py:153} INFO - Started process (PID=11277) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:50,705] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:11:50,707] {logging_mixin.py:115} INFO - [2023-03-10 09:11:50,707] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:50,717] {logging_mixin.py:115} INFO - [2023-03-10 09:11:50,714] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8
    ) as dag:
             ^
IndentationError: expected an indented block
[2023-03-10 09:11:50,718] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:11:50,755] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.066 seconds
[2023-03-10 09:12:21,759] {processor.py:153} INFO - Started process (PID=11375) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:21,760] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:12:21,763] {logging_mixin.py:115} INFO - [2023-03-10 09:12:21,763] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:21,796] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:22,472] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,472] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climaticos
[2023-03-10 09:12:22,484] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,484] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climaticos
[2023-03-10 09:12:22,492] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,492] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climaticos
[2023-03-10 09:12:22,492] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,492] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:12:22,501] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,501] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-03-10 09:12:22,509] {logging_mixin.py:115} INFO - [2023-03-10 09:12:22,508] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:12:22,543] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.797 seconds
[2023-03-10 09:12:53,279] {processor.py:153} INFO - Started process (PID=11415) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:53,280] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:12:53,281] {logging_mixin.py:115} INFO - [2023-03-10 09:12:53,280] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:53,287] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:12:53,324] {logging_mixin.py:115} INFO - [2023-03-10 09:12:53,324] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:12:53,341] {logging_mixin.py:115} INFO - [2023-03-10 09:12:53,341] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:12:53,358] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.081 seconds
[2023-03-10 09:13:28,455] {processor.py:153} INFO - Started process (PID=11466) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:13:28,462] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:13:28,464] {logging_mixin.py:115} INFO - [2023-03-10 09:13:28,463] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:13:28,495] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:13:28,564] {logging_mixin.py:115} INFO - [2023-03-10 09:13:28,564] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:13:28,576] {logging_mixin.py:115} INFO - [2023-03-10 09:13:28,576] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:13:28,602] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.158 seconds
[2023-03-10 09:14:00,616] {processor.py:153} INFO - Started process (PID=11616) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:00,619] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:14:00,619] {logging_mixin.py:115} INFO - [2023-03-10 09:14:00,619] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:00,625] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:00,657] {logging_mixin.py:115} INFO - [2023-03-10 09:14:00,657] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:14:00,669] {logging_mixin.py:115} INFO - [2023-03-10 09:14:00,669] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:14:00,682] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.069 seconds
[2023-03-10 09:14:31,722] {processor.py:153} INFO - Started process (PID=11658) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:31,724] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:14:31,726] {logging_mixin.py:115} INFO - [2023-03-10 09:14:31,726] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:31,754] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:14:31,786] {logging_mixin.py:115} INFO - [2023-03-10 09:14:31,786] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:14:31,806] {logging_mixin.py:115} INFO - [2023-03-10 09:14:31,806] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:14:31,818] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.107 seconds
[2023-03-10 09:15:04,425] {processor.py:153} INFO - Started process (PID=11698) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:04,428] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:15:04,430] {logging_mixin.py:115} INFO - [2023-03-10 09:15:04,429] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:04,436] {logging_mixin.py:115} INFO - [2023-03-10 09:15:04,434] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 3
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2023-03-10 09:15:04,436] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:04,473] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.062 seconds
[2023-03-10 09:15:38,764] {processor.py:153} INFO - Started process (PID=11754) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:38,772] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:15:38,772] {logging_mixin.py:115} INFO - [2023-03-10 09:15:38,772] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:38,788] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:15:38,803] {logging_mixin.py:115} INFO - [2023-03-10 09:15:38,802] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:15:38,822] {logging_mixin.py:115} INFO - [2023-03-10 09:15:38,822] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:15:38,839] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.078 seconds
[2023-03-10 09:16:13,363] {processor.py:153} INFO - Started process (PID=11833) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:13,367] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:16:13,369] {logging_mixin.py:115} INFO - [2023-03-10 09:16:13,369] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:13,377] {logging_mixin.py:115} INFO - [2023-03-10 09:16:13,375] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 17
    tarefa_2 = PythonOperator(
                              ^
IndentationError: unindent does not match any outer indentation level
[2023-03-10 09:16:13,379] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:13,412] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.060 seconds
[2023-03-10 09:16:52,207] {processor.py:153} INFO - Started process (PID=11933) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:52,209] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:16:52,210] {logging_mixin.py:115} INFO - [2023-03-10 09:16:52,209] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:52,211] {logging_mixin.py:115} INFO - [2023-03-10 09:16:52,211] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 17
    def extrai_dados
                    ^
IndentationError: unindent does not match any outer indentation level
[2023-03-10 09:16:52,212] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:16:52,230] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.026 seconds
[2023-03-10 09:17:24,913] {processor.py:153} INFO - Started process (PID=11987) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:17:24,915] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:17:24,917] {logging_mixin.py:115} INFO - [2023-03-10 09:17:24,917] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:17:24,927] {logging_mixin.py:115} INFO - [2023-03-10 09:17:24,923] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 17
    def extrai_dados():
                       ^
IndentationError: unindent does not match any outer indentation level
[2023-03-10 09:17:24,928] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:17:24,982] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.082 seconds
[2023-03-10 09:18:01,889] {processor.py:153} INFO - Started process (PID=12040) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:01,893] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:18:01,894] {logging_mixin.py:115} INFO - [2023-03-10 09:18:01,894] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:01,900] {logging_mixin.py:115} INFO - [2023-03-10 09:18:01,898] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 21
    def extrai_dados():
                       ^
IndentationError: unindent does not match any outer indentation level
[2023-03-10 09:18:01,900] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:01,925] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.047 seconds
[2023-03-10 09:18:33,514] {processor.py:153} INFO - Started process (PID=12146) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:33,517] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:18:33,520] {logging_mixin.py:115} INFO - [2023-03-10 09:18:33,519] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:33,528] {logging_mixin.py:115} INFO - [2023-03-10 09:18:33,525] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 21
    def extrai_dados():
                       ^
IndentationError: unindent does not match any outer indentation level
[2023-03-10 09:18:33,529] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:18:33,565] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.065 seconds
[2023-03-10 09:19:05,022] {processor.py:153} INFO - Started process (PID=12227) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:05,024] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:19:05,026] {logging_mixin.py:115} INFO - [2023-03-10 09:19:05,025] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:05,040] {logging_mixin.py:115} INFO - [2023-03-10 09:19:05,040] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:19:05,041] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:05,059] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.048 seconds
[2023-03-10 09:19:40,072] {processor.py:153} INFO - Started process (PID=12268) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:40,076] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:19:40,078] {logging_mixin.py:115} INFO - [2023-03-10 09:19:40,077] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:40,102] {logging_mixin.py:115} INFO - [2023-03-10 09:19:40,101] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:19:40,103] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:19:40,125] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.065 seconds
[2023-03-10 09:20:11,321] {processor.py:153} INFO - Started process (PID=12317) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:11,323] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:20:11,324] {logging_mixin.py:115} INFO - [2023-03-10 09:20:11,324] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:11,329] {logging_mixin.py:115} INFO - [2023-03-10 09:20:11,328] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 40
    ) 
    ^
SyntaxError: invalid syntax
[2023-03-10 09:20:11,330] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:11,365] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.052 seconds
[2023-03-10 09:20:43,548] {processor.py:153} INFO - Started process (PID=12391) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:43,550] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:20:43,552] {logging_mixin.py:115} INFO - [2023-03-10 09:20:43,552] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:43,586] {logging_mixin.py:115} INFO - [2023-03-10 09:20:43,583] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:20:43,587] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:20:43,616] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.081 seconds
[2023-03-10 09:21:16,243] {processor.py:153} INFO - Started process (PID=12474) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:16,246] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:21:16,249] {logging_mixin.py:115} INFO - [2023-03-10 09:21:16,248] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:16,282] {logging_mixin.py:115} INFO - [2023-03-10 09:21:16,280] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:21:16,282] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:16,309] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.081 seconds
[2023-03-10 09:21:49,932] {processor.py:153} INFO - Started process (PID=12533) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:49,934] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:21:49,934] {logging_mixin.py:115} INFO - [2023-03-10 09:21:49,934] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:49,944] {logging_mixin.py:115} INFO - [2023-03-10 09:21:49,943] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:21:49,944] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:21:49,960] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.031 seconds
[2023-03-10 09:22:27,311] {processor.py:153} INFO - Started process (PID=12641) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:22:27,313] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:22:27,314] {logging_mixin.py:115} INFO - [2023-03-10 09:22:27,314] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:22:27,317] {logging_mixin.py:115} INFO - [2023-03-10 09:22:27,316] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 4
    from airflow
                ^
SyntaxError: invalid syntax
[2023-03-10 09:22:27,318] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:22:27,350] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.042 seconds
[2023-03-10 09:23:02,778] {processor.py:153} INFO - Started process (PID=12740) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:02,780] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:23:02,781] {logging_mixin.py:115} INFO - [2023-03-10 09:23:02,780] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:02,790] {logging_mixin.py:115} INFO - [2023-03-10 09:23:02,789] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:23:02,790] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:02,807] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.034 seconds
[2023-03-10 09:23:37,173] {processor.py:153} INFO - Started process (PID=12792) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:37,179] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:23:37,181] {logging_mixin.py:115} INFO - [2023-03-10 09:23:37,181] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:37,214] {logging_mixin.py:115} INFO - [2023-03-10 09:23:37,212] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:23:37,214] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:23:37,244] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.083 seconds
[2023-03-10 09:24:12,587] {processor.py:153} INFO - Started process (PID=13001) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:12,589] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:24:12,589] {logging_mixin.py:115} INFO - [2023-03-10 09:24:12,589] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:12,599] {logging_mixin.py:115} INFO - [2023-03-10 09:24:12,598] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:24:12,599] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:12,616] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.035 seconds
[2023-03-10 09:24:47,665] {processor.py:153} INFO - Started process (PID=13216) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:47,669] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:24:47,671] {logging_mixin.py:115} INFO - [2023-03-10 09:24:47,671] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:47,704] {logging_mixin.py:115} INFO - [2023-03-10 09:24:47,702] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:24:47,705] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:24:47,736] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.083 seconds
[2023-03-10 09:25:23,676] {processor.py:153} INFO - Started process (PID=13276) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:25:23,682] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:25:23,685] {logging_mixin.py:115} INFO - [2023-03-10 09:25:23,684] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:25:23,708] {logging_mixin.py:115} INFO - [2023-03-10 09:25:23,707] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-10 09:25:23,708] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:25:23,730] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.069 seconds
[2023-03-10 09:28:19,518] {processor.py:153} INFO - Started process (PID=13881) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:19,519] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:28:19,520] {logging_mixin.py:115} INFO - [2023-03-10 09:28:19,520] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:19,946] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:19,978] {logging_mixin.py:115} INFO - [2023-03-10 09:28:19,978] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:28:19,990] {logging_mixin.py:115} INFO - [2023-03-10 09:28:19,990] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:28:20,013] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.497 seconds
[2023-03-10 09:28:57,331] {processor.py:153} INFO - Started process (PID=14338) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:57,333] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:28:57,333] {logging_mixin.py:115} INFO - [2023-03-10 09:28:57,333] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:57,644] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:28:57,654] {logging_mixin.py:115} INFO - [2023-03-10 09:28:57,654] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:28:57,668] {logging_mixin.py:115} INFO - [2023-03-10 09:28:57,668] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:28:57,680] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.352 seconds
[2023-03-10 09:29:27,135] {processor.py:153} INFO - Started process (PID=14539) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:29:27,135] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:29:27,136] {logging_mixin.py:115} INFO - [2023-03-10 09:29:27,135] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:29:27,575] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:29:27,618] {logging_mixin.py:115} INFO - [2023-03-10 09:29:27,618] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:29:27,635] {logging_mixin.py:115} INFO - [2023-03-10 09:29:27,634] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:29:27,653] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.522 seconds
[2023-03-10 09:30:05,823] {processor.py:153} INFO - Started process (PID=14906) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:05,826] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:30:05,828] {logging_mixin.py:115} INFO - [2023-03-10 09:30:05,828] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:06,110] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:06,118] {logging_mixin.py:115} INFO - [2023-03-10 09:30:06,118] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:30:06,131] {logging_mixin.py:115} INFO - [2023-03-10 09:30:06,131] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:30:06,141] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.328 seconds
[2023-03-10 09:30:37,203] {processor.py:153} INFO - Started process (PID=15156) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:37,205] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:30:37,208] {logging_mixin.py:115} INFO - [2023-03-10 09:30:37,207] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:37,513] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:30:37,522] {logging_mixin.py:115} INFO - [2023-03-10 09:30:37,522] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:30:37,537] {logging_mixin.py:115} INFO - [2023-03-10 09:30:37,537] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:30:37,548] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.357 seconds
[2023-03-10 09:31:12,392] {processor.py:153} INFO - Started process (PID=15298) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:31:12,396] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:31:12,398] {logging_mixin.py:115} INFO - [2023-03-10 09:31:12,398] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:31:12,749] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:31:12,758] {logging_mixin.py:115} INFO - [2023-03-10 09:31:12,758] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:31:12,771] {logging_mixin.py:115} INFO - [2023-03-10 09:31:12,771] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:31:12,788] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.406 seconds
[2023-03-10 09:32:25,941] {processor.py:153} INFO - Started process (PID=15574) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:32:25,943] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:32:25,943] {logging_mixin.py:115} INFO - [2023-03-10 09:32:25,943] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:32:26,345] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:32:26,359] {logging_mixin.py:115} INFO - [2023-03-10 09:32:26,358] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:32:26,379] {logging_mixin.py:115} INFO - [2023-03-10 09:32:26,379] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:32:26,396] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.457 seconds
[2023-03-10 09:33:04,469] {processor.py:153} INFO - Started process (PID=15891) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:04,472] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:33:04,473] {logging_mixin.py:115} INFO - [2023-03-10 09:33:04,473] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:04,721] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:04,748] {logging_mixin.py:115} INFO - [2023-03-10 09:33:04,748] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:33:04,758] {logging_mixin.py:115} INFO - [2023-03-10 09:33:04,758] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-02-06T00:00:00+00:00, run_after=2023-02-13T00:00:00+00:00
[2023-03-10 09:33:04,772] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.312 seconds
[2023-03-10 09:33:38,062] {processor.py:153} INFO - Started process (PID=16239) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:38,063] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:33:38,065] {logging_mixin.py:115} INFO - [2023-03-10 09:33:38,065] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:38,456] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:33:38,465] {logging_mixin.py:115} INFO - [2023-03-10 09:33:38,465] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:33:38,483] {logging_mixin.py:115} INFO - [2023-03-10 09:33:38,483] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:33:38,497] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.443 seconds
[2023-03-10 09:34:24,307] {processor.py:153} INFO - Started process (PID=16406) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:34:24,308] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:34:24,309] {logging_mixin.py:115} INFO - [2023-03-10 09:34:24,308] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:34:24,686] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:34:24,694] {logging_mixin.py:115} INFO - [2023-03-10 09:34:24,694] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:34:24,707] {logging_mixin.py:115} INFO - [2023-03-10 09:34:24,707] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:34:24,718] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.413 seconds
[2023-03-10 09:35:03,247] {processor.py:153} INFO - Started process (PID=16797) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:03,250] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:35:03,251] {logging_mixin.py:115} INFO - [2023-03-10 09:35:03,251] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:03,498] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:03,507] {logging_mixin.py:115} INFO - [2023-03-10 09:35:03,506] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:35:03,520] {logging_mixin.py:115} INFO - [2023-03-10 09:35:03,520] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:35:03,529] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.292 seconds
[2023-03-10 09:35:39,224] {processor.py:153} INFO - Started process (PID=16861) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:39,226] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:35:39,226] {logging_mixin.py:115} INFO - [2023-03-10 09:35:39,226] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:39,228] {logging_mixin.py:115} INFO - [2023-03-10 09:35:39,227] {dagbag.py:320} ERROR - Failed to import: /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py", line 11
    start_date=pendulum.datetime(2023, 2, , tz="UTC"),
                                          ^
SyntaxError: invalid syntax
[2023-03-10 09:35:39,228] {processor.py:653} WARNING - No viable dags retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:39,244] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.022 seconds
[2023-03-10 09:35:58,374] {processor.py:153} INFO - Started process (PID=17046) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:58,375] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:35:58,375] {logging_mixin.py:115} INFO - [2023-03-10 09:35:58,375] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:58,716] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:35:58,726] {logging_mixin.py:115} INFO - [2023-03-10 09:35:58,726] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:35:58,744] {logging_mixin.py:115} INFO - [2023-03-10 09:35:58,744] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:35:58,769] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.397 seconds
[2023-03-10 09:36:34,475] {processor.py:153} INFO - Started process (PID=17427) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:36:34,477] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:36:34,478] {logging_mixin.py:115} INFO - [2023-03-10 09:36:34,477] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:36:34,765] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:36:34,773] {logging_mixin.py:115} INFO - [2023-03-10 09:36:34,773] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:36:34,786] {logging_mixin.py:115} INFO - [2023-03-10 09:36:34,786] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:36:34,804] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.333 seconds
[2023-03-10 09:40:08,026] {processor.py:153} INFO - Started process (PID=17861) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:08,028] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:40:08,028] {logging_mixin.py:115} INFO - [2023-03-10 09:40:08,028] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:08,378] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:08,418] {logging_mixin.py:115} INFO - [2023-03-10 09:40:08,418] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:40:08,435] {logging_mixin.py:115} INFO - [2023-03-10 09:40:08,435] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:40:08,452] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.429 seconds
[2023-03-10 09:40:45,400] {processor.py:153} INFO - Started process (PID=18313) to work on /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:45,403] {processor.py:641} INFO - Processing file /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py for tasks to queue
[2023-03-10 09:40:45,404] {logging_mixin.py:115} INFO - [2023-03-10 09:40:45,404] {dagbag.py:507} INFO - Filling up the DagBag from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:45,657] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py
[2023-03-10 09:40:45,666] {logging_mixin.py:115} INFO - [2023-03-10 09:40:45,666] {dag.py:2379} INFO - Sync 1 DAGs
[2023-03-10 09:40:45,680] {logging_mixin.py:115} INFO - [2023-03-10 09:40:45,680] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-03-06T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-10 09:40:45,698] {processor.py:161} INFO - Processing /home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/dags/dado_climaticos.py took 0.306 seconds
